apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.metadata.name}.{.metadata.namespace}.svc.cluster.local:{.spec.ports[?(.name=="postgresql")].port}
  labels:
    template: postgresql-persistent-template
  name: {{ .Values.database_service_name }}
spec:
  clusterIP: None
  ports:
  - name: postgresql
    nodePort: 0
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: {{ .Values.database_service_name }}
  sessionAffinity: None
  type: ClusterIP

